modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="gm"
version="1.0.0"
displayName="Goon Mod"
displayURL="https://mcreator.net"
credits="William, MCreator"
authors="William, MCreator"
description="The Gooncraft Mod"

[[dependencies.gm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




