name: Upload to CurseForge

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CurseForgeUploader (cfuploader)
        run: npm install -g cfuploader

      - name: Upload to CurseForge
        run: cfuploader --api-key ${{ secrets.CURSEFORGE_API_KEY }} --project-id 1225110 --file "releases/curr/gsm.jar" --changelog "changelog.txt" --release-type "release"
