name: Upload Mod to CurseForge on Release Publish

on:
  workflow_dispatch:
  release:
    types:
      - published  # Triggered when a release is published

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Upload the mod to CurseForge
      run: |
        curl -L -v -X POST -H "X-Api-Token: ${{ secrets.CURSEFORGE_API_TOKEN }}" -F "metadata={\"changelog\":\"${{ github.event.release.body }}\",\"changelogType\":\"markdown\",\"displayName\":\"${{ github.event.release.name }}\",\"releaseType\":\"alpha\",\"gameVersions\":[157, 158],\"isMarkedForManualRelease\":true}" -F "file=@releases/curr/gsm.jar" https://api.curseforge.com/v1/projects/1225110/upload-file
