name: Upload Mod to CurseForge on Release Publish

on:
  workflow_dispatch:
  release:
    types:
      - published  # Triggered when a release is published

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Upload the mod to CurseForge
      run: |
        curl -L -v -X POST -H "X-Api-Token: 5fee90ef-5579-49ef-9177-7e62fa79d333" -F "metadata={\"changelog\":\"Initial release\",\"changelogType\":\"markdown\",\"displayName\":\"Goon Mod \",\"releaseType\":\"alpha\",\"gameVersions\":[9990],\"isMarkedForManualRelease\":true}" -F "file=@releases/curr/gsm.jar" http://www.curseforge.com/api/projects/1225110/upload-file
