name: Build and Release Minecraft Mod

on:
  push:
    tags:
      - '*.*.*'  # Trigger only on version tags like 1.0.0

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Upload full project directory
        uses: actions/upload-artifact@v4
        with:
          name: full-project
          path: .

  Build:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Download full project
        uses: actions/download-artifact@v4
        with:
          name: full-project

      - name: Build the mod
        run: ./gradlew build

      - name: Upload built mod as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-mod
          path: build/libs/modid-*.jar  # Ensure to match your specific naming pattern

  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download built mod
        uses: actions/download-artifact@v4
        with:
          name: built-mod

      - name: Get latest version tag
        id: get_version
        run: echo "VERSION=$(git tag --sort=-v:refname | head -n 1)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: "*.jar"
          body: "Release notes for version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
