name: Build and Store Mod in Release Generation

on:
  push:
    tags:
      - '*.*.*'  # Triggered by tags like v1.0.0, v1.1.0, etc.

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v4.7.0
      with:
        java-version: 17  # Specify the version of Java (17 in your case)
        distribution: 'zulu'  # Specify the distribution, e.g., AdoptOpenJDK or zulu
        java-package: 'jdk'  # You can specify 'jdk' to get the full JDK package, or 'jre' if you want just the JRE
        architecture: 'x64'  # Specify the architecture, default is x64
        check-latest: true  # Optionally, check for the latest available version if you want

    - name: Upload gradlew and other necessary files as artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: gradle-setup
        path: .

        

  Build:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
    
    - name: Download gradle setup artifact
      uses: actions/download-artifact@v4.6.2
      with:
        name: gradle-setup

        
    - name: Build the mod
      run: |
        # Assuming you are using a build tool like Gradle or Maven
        # Replace with the actual build command for your project
        ./gradlew build  # Replace this with your build command if different
        echo "Mod built"

  Store-and-release:
    runs-on: ubuntu-latest
    needs: Build
    steps:

    - name: Download gradle setup artifact
      uses: actions/download-artifact@v4.6.2
      with:
        name: gradle-setup
    
    - name: Store the mod in releases/curr/gsm.jar
      run: |
        mkdir -p releases/curr
        LATEST_MOD=$(ls build/libs/modid-*.jar | sort -V | tail -n 1)
        cp "$LATEST_MOD" releases/curr/gsm.jar

    - name: Get the version tag dynamically
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0)  # Get the most recent tag
        echo "version=$VERSION" >> $GITHUB_ENV  # Set the version as an environment variable
    
    - name: Create a GitHub release
      run: |  # Provide authentication token for GitHub API
        gh release create ${{ env.version }} releases/curr/gsm.jar --title "Release ${{ env.version }}" --notes "Release notes for ${{ env.version }} go here."
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
    
